import json
import os
import datetime
import random

# Configuration
SYLLABUS_FILE = 'tools/hack_agent/syllabus_sample.json'
OUTPUT_CONTENT_DIR = 'content/docs/hack_prototype'
OUTPUT_DATA_DIR = 'static/data/generated'
START_DATE = datetime.date(2026, 1, 25)
# EXAM_DATE = datetime.date(2026, 4, 19) 
DAYS_TO_GENERATE = 3  # Generate only 3 days for prototype

def load_syllabus():
    with open(SYLLABUS_FILE, 'r', encoding='utf-8') as f:
        return json.load(f)

def generate_mock_questions(topic):
    """
    In a real scenario, this would call an LLM API:
    response = llm.generate(f"Create 3 difficult questions about {topic['title']}...")
    """
    questions = []
    for i in range(3):
        questions.append({
            "id": f"{topic['id']}_q{i+1}",
            "question": f"【AI生成】{topic['title']} に関する実践問題 {i+1}",
            "options": [
                f"{topic['title']}の正しい記述A",
                f"{topic['title']}の誤った記述B",
                f"{topic['title']}の誤った記述C",
                f"{topic['title']}の誤った記述D"
            ],
            "answer_index": 0,
            "explanation": f"これはAIがシラバス「{topic['description']}」に基づいて生成した解説です。正解はAです。",
            "difficulty": topic['weight'],
            "tags": ["AI生成", topic['title']]
        })
    return questions

def create_daily_content(date, topic, day_number):
    date_str = date.strftime('%Y-%m-%d')
    file_id = f"day_{day_number:03d}"  # e.g., day_001
    
    # 1. Generate Quiz Data (JSON)
    questions = generate_mock_questions(topic)
    json_filename = f"{file_id}.json"
    json_path = os.path.join(OUTPUT_DATA_DIR, json_filename)
    
    os.makedirs(OUTPUT_DATA_DIR, exist_ok=True)
    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(questions, f, indent=4, ensure_ascii=False)
    print(f"Generated Quiz Data: {json_path}")

    # 2. Generate Article (Markdown)
    md_filename = f"{file_id}.md"
    md_path = os.path.join(OUTPUT_CONTENT_DIR, md_filename)
    
    os.makedirs(OUTPUT_CONTENT_DIR, exist_ok=True)
    
    md_content = f"""---
title: "Day {day_number}: {topic['title']}"
date: {date_str}
draft: false
tags: ["SyllabusHack", "Day{day_number}", "{topic['title']}"]
summary: "【AI先生の指導】今日は「{topic['title']}」を完璧にしましょう。"
---

## 👩‍🏫 本日の学習テーマ: {topic['title']}

こんにちは！あなたのAIチューターです。
試験まであと少し。今日はシラバスの**「{topic['title']}」**について集中的に攻撃します。

### 📌 シラバスの定義
> {topic['description']}

### ⚔️ AI生成：本日の実戦問題
私が過去問の傾向を分析し、**あなたの弱点になりそうなポイント**を問題にしました。
全問正解するまで帰れませんよ？

{{{{< quiz category="generated/{file_id}" >}}}}

---
*Generated by Syllabus Hack Agent Teacher*
"""
    with open(md_path, 'w', encoding='utf-8') as f:
        f.write(md_content)
    print(f"Generated Article: {md_path}")

def main():
    syllabus = load_syllabus()
    topics = syllabus['topics']
    
    print(f"🤖 Agent Teacher Initialized.")
    print(f"📚 Course: {syllabus['exam_name']}")
    print(f"📅 Start Date: {START_DATE}")
    
    # Simple Scheduler: 1 Topic per Day
    current_date = START_DATE
    
    for i in range(DAYS_TO_GENERATE):
        topic = topics[i % len(topics)]
        create_daily_content(current_date, topic, i + 1)
        current_date += datetime.timedelta(days=1)
        
    print("✅ Prototype Content Generation Complete!")

if __name__ == "__main__":
    main()
